### Creates a new Reports
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1980,
  "mileage": 100000,
  "lng": 0,
  "lat": 0,
  "price": 500000
}

###
PATCH  http://localhost:3000/reports/5
Content-Type: application/json

{
  "approved": true
}

###
GET  http://localhost:3000/reports?make=make&model=model&year=2023&lng=1&lat=1&mileage=1000